- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/BatchDbConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/CourseDbConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/GradStudentDbConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/ProgramDbConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/RestWebClient.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/TraxDbConfig.java
- tools/openshift/api.dc.yaml
timeout issue and memory issue have been fixed on openshift.
> timeout issue and memory issue have been fixed.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/BatchJobConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/entity/assessment/AssessmentRequirementEntity.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/entity/student/GraduationStatusEntity.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/listener/CourseRequirementDataConversionJobCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/ConversionCourseSummaryDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/processor/AssessmentRequirementCreator.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/processor/CourseRequirementCreator.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/processor/DataConversionCourseRequirementProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/reader/DataConversionCourseRequirementReader.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/assessment/AssessmentService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/conv/DataConversionService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/course/CourseService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/writer/DataConversionCourseRequirementWriter.java
Multiple job steps are set for CourseRequirement Load in spring batch.
> Multiple job steps are set for CourseRequirement Load in spring batch.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/entity/conv/GraduationCourseKey.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/course/CourseService.java
Bug fix on handling blank values on course level of CourseRequirement.
> Bug fix on handling blank values on course level of CourseRequirement.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/entity/conv/GraduationCourseEntity.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/course/CourseService.java
Adult(1950) program requirements load is added.
> Adult(1950) program requirements are initially added.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/CustomRequestBodyAdviceAdapter.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/GradDataConvConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/RequestInterceptor.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/RestWebClient.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiConstants.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/LogHelper.java
- api/src/main/resources/application.yaml
- tools/openshift/api.dc.yaml
Splunk feature is initially added.
> Splunk feature is initially added.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/AssessmentDbConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/BatchDbConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/GradStudentDbConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/ProgramDbConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/TraxDbConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/entity/student/GraduationStudentRecordEntity.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/entity/student/GraduationStudentRecordHistoryEntity.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentService.java
GraduationStudentRecord & History schema change are applied.
> GraduationStudentRecord & History schema changes are applied.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/entity/course/CourseRequirementCodeEntity.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/entity/course/CourseRestrictionEntity.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/conv/DataConversionService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/course/CourseService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/DataConversionServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentServiceTest.java
1. Do not convert null trax date for expiry date in Course Restriction.
2. Blank (null or empty) should be handled as space in Data Conversion.
> GRAD2-858 & course level blank value issue are resolved

- api/src/main/db/dataConversion.sql
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/entity/student/GraduationStudentRecordEntity.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/entity/trax/GraduationCourseEntity.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/ConvGradStudent.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/ConversionStudentSummaryDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/repository/course/CourseRequirementRepository.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/repository/trax/TraxStudentsLoadRepository.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/conv/DataConversionService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/course/CourseService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/DataConversionServiceTest.java
Course Requirements & Students load for 1986 grad program.
> Updates for 1986 grad program.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/repository/trax/TraxStudentsLoadRepository.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/conv/DataConversionService.java
trax_students_pen_update table is used to load trax students for pen update.
> The new table is applied for adding missing students.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/reader/DataConversionAllTraxStudentsReader.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/conv/DataConversionService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/AssessmentServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/DataConversionServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/ProgramServiceTest.java
Removed some warnings and logs, and provided more junit tests.
> Cleanup codes and more coverage works.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/BatchJobConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/reader/DataConversionAllTraxStudentsReader.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiConstants.java
- api/src/main/resources/application.yaml
- api/src/test/resources/application.yaml
Page size for paging is dynamic and configurable in openshift.
> Updated to set page_size configurable in openshift.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/repository/trax/TraxStudentsLoadRepository.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/trax/TraxService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentServiceWithMockRepositoryTest.java
Mincode validation is added for student load.
> Mincode validation is added for student load.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/processor/BasePartitionHandlerCreator.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/processor/StudentPartitionHandlerCreator.java
Bug fix on aggregating summary from each partition.
> Bug fix on aggregating summary from each partition.

- api/src/test/java/ca/bc/gov/educ/api/dataconversion/config/ConvDbConfig.java
Fixed the build failure in openshift.
> Fixed the build failure in openshift.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/choreographer/ChoreographEventHandler.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/messaging/NatsConnection.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/EventHandlerDelegatorService.java
Updates to reduce INFO level Logs.
> Updates to reduce INFO level Logs.

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/repository/trax/TraxStudentsLoadRepository.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/conv/DataConversionService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiConstants.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/DataConversionServiceTest.java
Clean up codes & jdbc driver upgrade
> Clean up codes & jdbc driver upgrade

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/CourseRequirement.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/reader/DataConversionCourseRequirementReader.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/reader/DataConversionCourseRestrictionReader.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/course/CourseService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/DateConversionUtils.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiConstants.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiUtils.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/RestUtils.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/writer/DataConversionCourseRestrictionWriter.java
- api/src/main/resources/application.yaml
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/CourseServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/util/RestUtilsTest.java
- api/src/test/resources/application.yaml
Enhancements to handle blank course level in data conversion.
> Enhancements to handle blank course level in data conversion.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/RequestInterceptor.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/RestWebClient.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/messaging/jetstream/Subscriber.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiConstants.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/LogHelper.java
- api/src/main/resources/application.yaml
- api/src/test/resources/application.yaml
Updates to make Splunk logging optional in openshift.
> Make Splunk logging optional in openshift.

- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/AssessmentServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/CourseServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/DataConversionServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentServiceWithMockRepositoryTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/util/RestUtilsTest.java
Fixed the NATS connection error in unit tests.
> Fixed the NATS connection error in unit tests.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/RequestInterceptor.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/JwtUtil.java
just name is used from JWT to save username in transaction.
> just name is used from JWT to save username in transaction.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiConstants.java
- api/src/main/resources/application.yaml
Disable unnecessary loggings from connection pool.
> Disable unnecessary loggings from connection pool.

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/ConvDbConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/GradStudentDbConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiConstants.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/RestUtils.java
- api/src/main/resources/application.yaml
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/util/RestUtilsTest.java
- api/src/test/resources/application.yaml
Updates for SpringBoot upgrade to 2.7.1 & Oracle JDBC to 21.6.0.0.1
> Updates for SpringBoot upgrade to 2.7.1 & Oracle JDBC to 21.6.0.0.1

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/tsw/GraduationProgramCode.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/ReportService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/ReportServiceTest.java
- api/src/test/resources/json/gradstatus.json
GRAD2-1614 : removed assessmentReleaseDate and the logic around it.
> GRAD2-1614 : removed assessmentReleaseDate and the logic around it.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/course/CourseService.java
> GRAD2-1751: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/constant/Topics.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/messaging/jetstream/Subscriber.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/EventHandlerDelegatorService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiConstants.java
> Updates related to GRAD2-1708

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/ConvDbConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/GradStudentDbConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/entity/student/GraduationStudentRecordEntity.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/entity/student/GraduationStudentRecordHistoryEntity.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/ConvGradStudent.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentService.java
GRAD2-1717, GRAD2-1718: task is complete.
> GRAD2-1717, GRAD2-1718: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/ConvGradStudent.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentBaseService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/DataConversionServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentServiceWithMockRepositoryTest.java
- api/src/test/resources/mock_conv_grad_students.json
GRAD2-1714 & GRAD2-1719: tasks are complete
> GRAD2-1714 & GRAD2-1719: tasks are complete

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentServiceWithMockRepositoryTest.java
GRAD2-1763 : the task is complete
> GRAD2-1763 : the task is complete

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/course/CourseService.java
GRAD2-1785 : the task is complete.
> GRAD2-1785 : the task is complete.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/ConvGradStudent.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/ConversionStudentSummaryDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/tsw/School.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentService.java
> GRAD2-1836 & GRAD2-1841

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/entity/student/GraduationStudentRecordEntity.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/entity/student/GraduationStudentRecordHistoryEntity.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/ConvGradStudent.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentBaseService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiConstants.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/RestUtils.java
- api/src/main/resources/application.yaml
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentServiceWithMockRepositoryTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/util/RestUtilsTest.java
- api/src/test/resources/application.yaml
> GRAD2-1817 : task is complete

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/ConvGradStudent.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/ReportService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/ReportServiceTest.java
GRAD2-1846 : the task is initially implemented.
> GRAD2-1846 : the task is initially implemented.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/ConvGradStudent.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/StudentCommonDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/DateConversionUtils.java
> GRAD2-1846 : task is complete

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/course/CourseService.java
GRAD2-1867: the issue has been resolved.
> GRAD2-1867: the issue has been resolved.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/GraduationStudentRecord.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/StudentCommonDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/TranscriptStudentCourse.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/TranscriptStudentDemog.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/ReportService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentBaseService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/writer/StudentPartitionWriter.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/ReportServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentServiceTest.java
GRAD2-1954, 1934, 1935, 1936, 1937 : tasks are completed.
> GRAD2-1954, 1934, 1935, 1936, 1937 : tasks are completed.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/ConvDbConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/GraduationStudentRecord.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiUtils.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentServiceTest.java
GRAD2-1935, 1936, 1937, 1938 : big fixes for the reopened issues.
> GRAD2-1935, 1936, 1937, 1938 : big fixes for the reopened issues.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/BatchJobConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/ConvDbConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/CourseRequirementDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/CourseProcess.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/process/CourseProcessTest.java
GRAD2-1968 : task is completed, and cleaned up the unnecessary codes of db settings for old JDBC driver.
> GRAD2-1968 : task is completed, and clean up the unnecessary codes.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/BatchJobConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/constant/BatchStatusEnum.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/BatchJobResponse.java
> Make batch jobs async.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/BatchJobConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/ConversionStudentSummaryDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/scheduler/JetStreamEventScheduler.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiConstants.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/RestUtils.java
- api/src/main/resources/application.yaml
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcessTest.java
- api/src/test/resources/application.yaml
GRAD2-1982 : task is completed and clean up unused codes.
> GRAD2-1982 : task is completed and clean up unused codes.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcessTest.java
GRAD2-1983 : task is completed
> GRAD2-1983 : task is completed

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/CourseProcess.java
> GRADT-653: bug fix

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/constant/StudentLoadType.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/ConvGradStudent.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/processor/StudentPartitionProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentBaseService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/process/DataConversionProcessTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcessTest.java
> GRAD2-1987: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentBaseService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/RestUtils.java
- api/src/main/resources/application.yaml
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/process/AssessmentProcessTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/process/DataConversionProcessTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcessTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/util/RestUtilsTest.java
GRAD2-1997, GRAD2-1988 & GRAD2-2000: tasks are complete
> GRAD2-1997, GRAD2-1988 & GRAD2-2000: tasks are complete

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcessTest.java
> GRAD2-2001: task is complete

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/StudentGradDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentGraduationUpdateEventService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcessTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentGraduationUpdateEventServiceTest.java
> GRAD2-1861: task is complete

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentBaseService.java
> GRAD2-2012: task is complete

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/ConvGradStudent.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
> GRAD2-2013: task is complete

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiConstants.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/RestUtils.java
- api/src/main/resources/application.yaml
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcessTest.java
- api/src/test/resources/application.yaml
> GRAD2-2025: task is complete

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/tsw/School.java
GRAD2-2036: the issue is resolved.
> GRAD2-2036: the issue is resolved.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/choreographer/ChoreographEventHandler.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/constant/StudentLoadType.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/processor/StudentPartitionProcessor.java
> GRAD2-1964: task is complete

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/CourseProcess.java
GRAD2-2020 & GRAD2-2125: tasks are complete.
> GRAD2-2020 & GRAD2-2125: tasks are complete.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/CourseProcess.java
> GRAD2-2119: task is complete

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/StudentGradDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentBaseService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentGraduationUpdateEventService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcessTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentGraduationUpdateEventServiceTest.java
GRAD2-2103 & GRAD2-2143: tasks are complete
> GRAD2-2103 & GRAD2-2143: tasks are complete

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
GRAD2-2103: bug fix on DD creation.
> GRAD2-2103: bug fix on DD creation.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
GRAD2-2148: the issue is resolved.
> GRAD2-2148: the issue is resolved.

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
> Grad release 1.1.7

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/CourseProcess.java
> GRAD2-2156: task is complete

- api/pom.xml
Sync from main - GRAD2-2156 - Hotfix 1.1.8
> Sync from main - GRAD2-2156 - Hotfix 1.1.8

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/StudentCommonDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/StudentGradDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentFrenchImmersionEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentGraduationUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentXProgramEventService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcessTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentGraduationUpdateEventServiceTest.java
> GRAD2-2172: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/StudentCommonDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/StudentGradDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/TraxGraduationUpdateDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentGraduationUpdateEventService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcessTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentGraduationUpdateEventServiceTest.java
> GRAD2-2191: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/StudentCommonDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/StudentGradDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentGraduationUpdateEventService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentGraduationUpdateEventServiceTest.java
GRAD2-2199: fixed the issues found from Dev test.
> GRAD2-2199: fixed the issues found from Dev test.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
GRAD2-2172: bug fix on NPE when retrieving student optional programs.
> GRAD2-2172: bug fix on NPE when retrieving student optional programs.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentBaseService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentGraduationUpdateEventService.java
GRAD2-2338: task is completed.
> GRAD2-2338: task is completed.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/CourseProcess.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentAssessmentUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentCourseUpdateEventService.java
> GRAD2-2365: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/ReportProcess.java
HD-23020-P3 - GRAD - Service Request - Locally Developed Courses on 2023 Transcripts Missing Parenthesis
> GRAD2-2392

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/exception/ServiceException.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/ReportProcess.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/Generated.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/RestUtils.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/util/RestUtilsTest.java
HD-21559-GRAD - P3 - GRAD is creating blank transcripts
> GRAD2-2306, GRAD2-2242

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/CourseProcess.java
> GRAD2-2402: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/choreographer/ChoreographEventHandler.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/messaging/jetstream/Subscriber.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/scheduler/JetStreamEventScheduler.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/ChoreographedEventPersistenceService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/EventHandlerDelegatorService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentAssessmentUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentCourseUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentDemographicsUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentFrenchImmersionEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentGraduationUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentStatusUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentXProgramEventService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentAssessmentUpdateEventServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentCourseUpdateEventServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentDemographicsUpdateEventServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentFrenchImmersionEventServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentGraduationUpdateEventServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentStatusUpdateEventServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentXProgramEventServiceTest.java
> GRAD2-2423: task is complete.

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/choreographer/ChoreographEventHandler.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/messaging/jetstream/Subscriber.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/scheduler/JetStreamEventScheduler.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/ChoreographedEventPersistenceService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/EventHandlerDelegatorService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentAssessmentUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentCourseUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentDemographicsUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentFrenchImmersionEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentGraduationUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentStatusUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentXProgramEventService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentAssessmentUpdateEventServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentCourseUpdateEventServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentDemographicsUpdateEventServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentFrenchImmersionEventServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentGraduationUpdateEventServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentStatusUpdateEventServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentXProgramEventServiceTest.java
> Grad release 1.11.0

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/CourseProcess.java
GRAD2-2386: task is completed.
> GRAD2-2386: task is completed.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
GRAD2-2426: task is completed.
> GRAD2-2426: task is completed.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/BatchJobConfig.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/repository/EventRepository.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/scheduler/PurgeOldRecordsScheduler.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiConstants.java
- api/src/main/resources/application.yaml
- api/src/test/resources/application.yaml
> GRAD2-2430: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentAssessmentUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentBaseService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentCourseUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentDemographicsUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentFrenchImmersionEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentXProgramEventService.java
> GRAD2-2072: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentGraduationUpdateEventService.java
> GRAD2-2425: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/ReportProcess.java
(GRAD) - P3 Incident: 1950 program includes Non-Completion Reason "506 - N/A"
> GRAD2-2477

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/StudentCommonDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentBaseService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentGraduationUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentStatusUpdateEventService.java
> GRAD2-2479: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentGraduationUpdateEventService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentGraduationUpdateEventServiceTest.java
GRAD2-2479: new requirements are implemented.
> GRAD2-2479: new requirements are implemented.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentDemographicsUpdateEventService.java
GRAD2-2493: removed the change detection for demographics at field level.
> GRAD2-2493: removed the change detection for demographics at field level.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/RestUtils.java
GRAD2-2465 - Delete a student and related data
> GRAD2-2465 - Delete a student and related data

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiConstants.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/RestUtils.java
- api/src/main/resources/application.yaml
- api/src/test/resources/application.yaml
> GRAD2-2587

- .github/workflows/build.from.main.branch.deploy.to.dev.yml
- .github/workflows/build.from.release.branch.deploy.to.dev.yml
- .github/workflows/on.pr.yml
> Upgrade ZAPSCAN to 0.7.0

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/choreographer/ChoreographEventHandler.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/constant/EventType.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/StudentGradDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/TraxGraduationUpdateDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/model/TraxStudentStatusUpdateDTO.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentGraduationUpdateEventService.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentStatusUpdateEventService.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcessTest.java
- api/src/test/java/ca/bc/gov/educ/api/dataconversion/service/StudentGraduationUpdateEventServiceTest.java
GRAD2-2546: task is completed.
> GRAD2-2546: task is completed.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentBaseService.java
> GRAD2-2805: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
> GRAD2-3006: task is complete.

- api/pom.xml
- api/src/main/resources/application.yaml
> Grad release

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/process/StudentProcess.java
> GRAD2-3011: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/dataconversion/service/student/StudentGraduationUpdateEventService.java
> GRAD2-3169: task is complete.

- .github/workflows/on.pr.yml
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/RequestInterceptor.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/config/RestWebClient.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/EducGradDataConversionApiConstants.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/LogHelper.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/RestUtils.java
- api/src/main/java/ca/bc/gov/educ/api/dataconversion/util/ThreadLocalStateUtil.java
> Grad2-3284 Set request headers
